# Basic Data Exploration and Cleaning using Pandas

## Data Engineering Assignment

### Submitted By:
Rishikesh Kapoor

# Importing Required Libraries

In [1]:
import pandas as pd

# Reading csv file

In [2]:
df = pd.read_csv("data/tshirts.csv")

In [3]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,"""â‚¹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,NaN,"""â‚¹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Truâ–ˆâ–ˆâ–ˆm Râ–ˆâ–ˆâ–ˆil,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Shoâ–ˆâ–ˆâ–ˆo. â–ˆâ–ˆâ–ˆ-10â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,NaN,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,"""â‚¹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,"""â‚¹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUNâ–ˆâ–ˆâ–ˆE Câ–ˆâ–ˆâ–ˆTIOâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,No.â–ˆâ–ˆâ–ˆhanâ–ˆâ–ˆâ–ˆGouâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999,NaN,"""â‚¹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
6,919032,Roadster,Off-White Black Striped Speckled Pure Cotton ...,3.8,641,899,NaN,"""â‚¹899.00""",INR,http://assets.myntassets.com/assets/images/919...,...,"{""1_star"":73,""2_stars"":46,""3_stars"":86,""4_star...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""rw-919032_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799,40.0,"""â‚¹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599,50.0,"""â‚¹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"{""1_star"":36,""2_stars"":16,""3_stars"":46,""4_star...",NaN,NaN,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
9,20355284,Roadster,The Life Co. Round Neck Raglan Sleeves Typogr...,4.2,74,999,53.0,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":6,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
10,18818696,Tommy Hilfiger,Men White & Black Brand Logo Printed Organic C...,4.4,58,1999,40.0,"""â‚¹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":6,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""37.4in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
11,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1,994,799,50.0,"""â‚¹799.00""",INR,http://assets.myntassets.com/assets/images/921...,...,"{""1_star"":74,""2_stars"":41,""3_stars"":108,""4_sta...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-9213113_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
12,13511732,Puma,Men Black Solid Run Fav 1/4 Zip T-Shirt,4.4,167,3999,NaN,"""â‚¹3,999.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":11,""2_stars"":6,""3_stars"":7,""4_stars""...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""34.65in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
13,13591994,Camey,Men Maroon Solid Round Neck T-shirt,3.5,2,999,60.0,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""L"",""value"":""40.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
14,21439050,Kappa,Men Typography Printed Cotton T-shirt,3.2,9,599,30.0,"""â‚¹599.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
15,13615634,U.S. Polo Assn.,Men Red Solid Mandarin Collar T-shirt,4.5,69,1699,40.0,"""â‚¹1,699.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
16,13620624,Roadster,The Lifestyle Co Men White Brand Logo Appliqu...,4.0,154,1399,73.0,"""â‚¹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":12,""2_stars"":10,""3_stars"":18,""4_star...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
17,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499,NaN,"""â‚¹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":22,""2_stars"":11,""3_stars"":22,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
18,13621134,Roadster,The Lifestyle Co Men Rust Brown Solid Appliqu...,4.1,312,1399,50.0,"""â‚¹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":27,""2_stars"":18,""3_stars"":31,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
19,17686030,Allen Solly Tribe,Men Navy Blue Solid T-shirt,4.3,23,1499,30.0,"""â‚¹1,499.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
20,13616400,Arrow New York,Men Beige Printed Round Neck Pure Cotton T-shirt,4.8,13,899,25.0,"""â‚¹674.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
21,13480864,Aeropostale,Men White Printed Round Neck Pure Cotton T-shirt,4.2,13,1199,NaN,"""â‚¹1,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
22,13622338,Roadster,The Lifestyle Co Men Olive Green Solid Round ...,4.4,54,899,55.0,"""â‚¹404.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",MAIâ–ˆâ–ˆâ–ˆ KNâ–ˆâ–ˆâ–ˆEARâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,BEHâ–ˆâ–ˆâ–ˆ HPâ–ˆâ–ˆâ–ˆS Aâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
23,16295686,Miss & Chief,Boys Pack of 3 Printed T-shirt,3.9,7,1995,71.0,"""â‚¹578.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Home,"[{""size"":""2-3Y"",""value"":""24.4in"",""value_name"":...",NaN,Homâ–ˆâ–ˆâ–ˆandâ–ˆâ–ˆâ–ˆB/1â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
24,16298856,Friskers,Men Pack of 2 Printed Pure Cotton T-shirts,0.0,0,2998,59.0,"""â‚¹1,229.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Flyâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,Flaâ–ˆâ–ˆâ–ˆo 6â–ˆâ–ˆâ–ˆjayâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
25,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399,53.0,"""â‚¹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Rayâ–ˆâ–ˆâ–ˆd Lâ–ˆâ–ˆâ–ˆtedâ–ˆâ–ˆâ–ˆ,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",NaN,RAYâ–ˆâ–ˆâ–ˆD Lâ–ˆâ–ˆâ–ˆTEDâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
26,16292318,Bewakoof,Men White Printed Pockets T-shirt,4.2,17,1399,60.0,"""â‚¹549.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Tight""...",Bewâ–ˆâ–ˆâ–ˆof â–ˆâ–ˆâ–ˆndsâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Ploâ–ˆâ–ˆâ–ˆ8, â–ˆâ–ˆâ–ˆ Flâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
27,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1,103,699,58.0,"""â‚¹293.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":4,""2_stars"":8,""3_stars"":10,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Visâ–ˆâ–ˆâ–ˆ Stâ–ˆâ–ˆâ–ˆ,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,3rdâ–ˆâ–ˆâ–ˆoorâ–ˆâ–ˆâ–ˆo. â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
28,16923916,Monte Carlo,Women Pack Of 2 Blue & Peach Solid V-Neck Pure...,4.8,13,835,25.0,"""â‚¹835.00""",INR,http://assets.myntassets.com/assets/images/169...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
29,10143909,CHKOKKO,Chkokko Men Teal Green Solid Round Neck Traini...,3.7,53,1665,70.0,"""â‚¹499.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":10,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",DLAâ–ˆâ–ˆâ–ˆOSSâ–ˆâ–ˆâ–ˆIVAâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,FLOâ–ˆâ–ˆâ–ˆFIRâ–ˆâ–ˆâ–ˆ B â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
30,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""â‚¹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bodâ–ˆâ–ˆâ–ˆoveâ–ˆâ–ˆâ–ˆparâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",NaN,Bodâ–ˆâ–ˆâ–ˆoveâ–ˆâ–ˆâ–ˆparâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
31,10555034,Braveo,Men Navy Blue and Red Checked Round Neck Pure ...,0.0,0,1099,65.0,"""â‚¹384.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Braâ–ˆâ–ˆâ–ˆForâ–ˆâ–ˆâ–ˆes,"[{""size"":""S"",""value"":""37.5in"",""value_name"":""Ch...",NaN,SF.â–ˆâ–ˆâ–ˆ. 8â–ˆâ–ˆâ–ˆVadâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
32,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""â‚¹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Wesâ–ˆâ–ˆâ–ˆry â–ˆâ–ˆâ–ˆdinâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...",NaN,"Groâ–ˆâ–ˆâ–ˆ Flâ–ˆâ–ˆâ–ˆ, Nâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
33,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999,40.0,"""â‚¹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":17,""2_stars"":6,""3_stars"":26,""4_stars...","[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wesâ–ˆâ–ˆâ–ˆry â–ˆâ–ˆâ–ˆdinâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Groâ–ˆâ–ˆâ–ˆ Flâ–ˆâ–ˆâ–ˆ, Nâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799,40.0,"""â‚¹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lanâ–ˆâ–ˆâ–ˆrk â–ˆâ–ˆâ–ˆineâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41â–ˆâ–ˆâ–ˆ42/â–ˆâ–ˆâ–ˆblaâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""â‚¹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MADâ–ˆâ–ˆâ–ˆR Pâ–ˆâ–ˆâ–ˆT Pâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621â–ˆâ–ˆâ–ˆ 6nâ–ˆâ–ˆâ–ˆ khâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199,50.0,"""â‚¹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Ferâ–ˆâ–ˆâ–ˆid,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15â–ˆâ–ˆâ–ˆ SHâ–ˆâ–ˆâ–ˆMARâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""â‚¹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10Tâ–ˆâ–ˆâ–ˆLOOâ–ˆâ–ˆâ–ˆDU â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""â‚¹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10Tâ–ˆâ–ˆâ–ˆLOOâ–ˆâ–ˆâ–ˆDU â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [4]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,"""â‚¹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,NaN,"""â‚¹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Truâ–ˆâ–ˆâ–ˆm Râ–ˆâ–ˆâ–ˆil,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Shoâ–ˆâ–ˆâ–ˆo. â–ˆâ–ˆâ–ˆ-10â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,NaN,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,"""â‚¹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,"""â‚¹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUNâ–ˆâ–ˆâ–ˆE Câ–ˆâ–ˆâ–ˆTIOâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,No.â–ˆâ–ˆâ–ˆhanâ–ˆâ–ˆâ–ˆGouâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [5]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799,40.0,"""â‚¹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lanâ–ˆâ–ˆâ–ˆrk â–ˆâ–ˆâ–ˆineâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41â–ˆâ–ˆâ–ˆ42/â–ˆâ–ˆâ–ˆblaâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""â‚¹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MADâ–ˆâ–ˆâ–ˆR Pâ–ˆâ–ˆâ–ˆT Pâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621â–ˆâ–ˆâ–ˆ 6nâ–ˆâ–ˆâ–ˆ khâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199,50.0,"""â‚¹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Ferâ–ˆâ–ˆâ–ˆid,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15â–ˆâ–ˆâ–ˆ SHâ–ˆâ–ˆâ–ˆMARâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""â‚¹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10Tâ–ˆâ–ˆâ–ˆLOOâ–ˆâ–ˆâ–ˆDU â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""â‚¹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10Tâ–ˆâ–ˆâ–ˆLOOâ–ˆâ–ˆâ–ˆDU â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [6]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     object
 2   product_description     39 non-null     object
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     int64
 6   discount                32 non-null     float64
 7   final_price             39 non-null     object
 8   currency                39 non-null     object
 9   images                  39 non-null     object
 10  delivery_options        39 non-null     object
 11  product_details         39 non-null     object
 12  breadcrumbs             39 non-null     object
 13  product_specifications  39 non-null     object
 14  amount_of_stars         39 non-null     object
 15  what_customers_said     30 non-null     object
 16  seller_name             18 non-null     object
 17  sizes                   39 non-null     object
 18  videos                  10 non-null     object
 19  seller_information      18 non-null     object
 20  variations              14 non-null     object
 21  best_offer              39 non-null     object
 22  more_offers             39 non-null     object
 23  category                39 non-null     object
dtypes: float64(2), int64(3), object(19)
memory usage: 7.4+ KB

# Handling Missing Value

Missing values are identified and handled to improve data quality and consistency.

In [8]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [9]:
df = df.drop(columns=[
    'videos',
    'variations',
    'seller_information'
])

In [10]:
df['discount'] = df['discount'].fillna(0)

df['seller_name'] = df['seller_name'].fillna('Unknown')

df['what_customers_said'] = df['what_customers_said'].fillna('No Review')

In [11]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
best_offer                0
more_offers               0
category                  0
dtype: int64

# Checking Duplicate Records

In [12]:
df.duplicated().sum()

0

# Basic Data Operations (filter rows and select columns)

In [13]:
df['title']

0                         ether
1                Mast & Harbour
2                Mast & Harbour
3                   Urbano Plus
4                       ScoldMe
5                  UNDER ARMOUR
6                      Roadster
7                Tommy Hilfiger
8                         WROGN
9                      Roadster
10               Tommy Hilfiger
11                     Roadster
12                         Puma
13                        Camey
14                        Kappa
15              U.S. Polo Assn.
16                     Roadster
17                         Puma
18                     Roadster
19            Allen Solly Tribe
20               Arrow New York
21                  Aeropostale
22                     Roadster
23                 Miss & Chief
24                     Friskers
25                         Parx
26                     Bewakoof
27                Tokyo Talkies
28                  Monte Carlo
29                      CHKOKKO
30                      BULLMER
31                       Braveo
32    AMERICAN EAGLE OUTFITTERS
33                  Allen Solly
34                          max
35               Mad Over Print
36                     FERANOID
37               Flying Machine
38               Flying Machine
Name: title, dtype: object

In [14]:
df[['title', 'final_price']]

                        title    final_price
0                       ether  "â‚¹1,099.00"
1              Mast & Harbour    "â‚¹899.00"
2              Mast & Harbour    "â‚¹999.00"
3                 Urbano Plus  "â‚¹1,099.00"
4                     ScoldMe    "â‚¹719.00"
5                UNDER ARMOUR  "â‚¹1,999.00"
6                    Roadster    "â‚¹899.00"
7              Tommy Hilfiger  "â‚¹2,799.00"
8                       WROGN  "â‚¹1,599.00"
9                    Roadster    "â‚¹999.00"
10             Tommy Hilfiger  "â‚¹1,999.00"
11                   Roadster    "â‚¹799.00"
12                       Puma  "â‚¹3,999.00"
13                      Camey    "â‚¹999.00"
14                      Kappa    "â‚¹599.00"
15            U.S. Polo Assn.  "â‚¹1,699.00"
16                   Roadster  "â‚¹1,399.00"
17                       Puma  "â‚¹1,499.00"
18                   Roadster  "â‚¹1,399.00"
19          Allen Solly Tribe  "â‚¹1,499.00"
20             Arrow New York    "â‚¹674.00"
21                Aeropostale  "â‚¹1,199.00"
22                   Roadster    "â‚¹404.00"
23               Miss & Chief    "â‚¹578.00"
24                   Friskers  "â‚¹1,229.00"
25                       Parx    "â‚¹699.00"
26                   Bewakoof    "â‚¹549.00"
27              Tokyo Talkies    "â‚¹293.00"
28                Monte Carlo    "â‚¹835.00"
29                    CHKOKKO    "â‚¹499.00"
30                    BULLMER    "â‚¹799.00"
31                     Braveo    "â‚¹384.00"
32  AMERICAN EAGLE OUTFITTERS    "â‚¹359.00"
33                Allen Solly    "â‚¹599.00"
34                        max    "â‚¹479.00"
35             Mad Over Print    "â‚¹671.00"
36                   FERANOID    "â‚¹599.00"
37             Flying Machine    "â‚¹389.00"
38             Flying Machine    "â‚¹506.00"

In [15]:
df[df['discount'] > 50]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,best_offer,more_offers,category
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,"""â‚¹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":"" Multicoloured Tshirt for wom...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,SUNâ–ˆâ–ˆâ–ˆE Câ–ˆâ–ˆâ–ˆTIOâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
9,20355284,Roadster,The Life Co. Round Neck Raglan Sleeves Typogr...,4.2,74,999,53.0,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""description"":""Blue T-shirt for womenTypograp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":6,""2_stars"":1,""3_stars"":6,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
13,13591994,Camey,Men Maroon Solid Round Neck T-shirt,3.5,2,999,60.0,"""â‚¹999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""Maroon solid T-shirt has a rou...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""About the Brand"",""spec...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""L"",""value"":""40.0in"",""value_name"":""Ch...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
16,13620624,Roadster,The Lifestyle Co Men White Brand Logo Appliqu...,4.0,154,1399,73.0,"""â‚¹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""description"":""White solid T-shirt with brand...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":12,""2_stars"":10,""3_stars"":18,""4_star...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
22,13622338,Roadster,The Lifestyle Co Men Olive Green Solid Round ...,4.4,54,899,55.0,"""â‚¹404.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""description"":""Olive green solid T-shirt, has...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",MAIâ–ˆâ–ˆâ–ˆ KNâ–ˆâ–ˆâ–ˆEARâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
23,16295686,Miss & Chief,Boys Pack of 3 Printed T-shirt,3.9,7,1995,71.0,"""â‚¹578.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":""Pack of 3 Grey, Red and black ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Home,"[{""size"":""2-3Y"",""value"":""24.4in"",""value_name"":...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
24,16298856,Friskers,Men Pack of 2 Printed Pure Cotton T-shirts,0.0,0,2998,59.0,"""â‚¹1,229.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":""Pack of 2 T-shirtsYellow and n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Flyâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
25,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399,53.0,"""â‚¹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":""Black Tshirt for menConversati...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Rayâ–ˆâ–ˆâ–ˆd Lâ–ˆâ–ˆâ–ˆtedâ–ˆâ–ˆâ–ˆ,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
26,16292318,Bewakoof,Men White Printed Pockets T-shirt,4.2,17,1399,60.0,"""â‚¹549.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""description"":"" White Tshirt for men Conve...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""About the Brand"",""spec...","{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Tight""...",Bewâ–ˆâ–ˆâ–ˆof â–ˆâ–ˆâ–ˆndsâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
27,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1,103,699,58.0,"""â‚¹293.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":"" Yellow Tshirt for women Gr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":4,""2_stars"":8,""3_stars"":10,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Visâ–ˆâ–ˆâ–ˆ Stâ–ˆâ–ˆâ–ˆ,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
29,10143909,CHKOKKO,Chkokko Men Teal Green Solid Round Neck Traini...,3.7,53,1665,70.0,"""â‚¹499.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""description"":""Teal green solid training T-sh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":10,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",DLAâ–ˆâ–ˆâ–ˆOSSâ–ˆâ–ˆâ–ˆIVAâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
30,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""â‚¹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""description"":""Pack of 2Navy blue and turquoi...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""About the Brand""},{""sp...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Bodâ–ˆâ–ˆâ–ˆoveâ–ˆâ–ˆâ–ˆparâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
31,10555034,Braveo,Men Navy Blue and Red Checked Round Neck Pure ...,0.0,0,1099,65.0,"""â‚¹384.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""Navy Blue and Red checked T-sh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Braâ–ˆâ–ˆâ–ˆForâ–ˆâ–ˆâ–ˆes,"[{""size"":""S"",""value"":""37.5in"",""value_name"":""Ch...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
32,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""â‚¹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""White and Yellow printed T-shi...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Wesâ–ˆâ–ˆâ–ˆry â–ˆâ–ˆâ–ˆdinâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""â‚¹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":"" Black Tshirt for women Gra...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MADâ–ˆâ–ˆâ–ˆR Pâ–ˆâ–ˆâ–ˆT Pâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""â‚¹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":"" Black and white Tshirt for m...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""â‚¹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":""Rust Tshirt for menSolid with ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARVâ–ˆâ–ˆâ–ˆ LIâ–ˆâ–ˆâ–ˆTYLâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

# Creating derived columns

In [16]:
df[['initial_price', 'final_price']].head()

   initial_price    final_price
0           1099  "â‚¹1,099.00"
1            899    "â‚¹899.00"
2            999    "â‚¹999.00"
3           1099  "â‚¹1,099.00"
4           1598    "â‚¹719.00"

In [17]:
df['final_price'] = df['final_price'].str.replace('â‚¹', '')

df['final_price'] = df['final_price'].str.replace(',', '')

df['final_price'] = df['final_price'].str.replace('"', '')

df['final_price'] = df['final_price'].astype(float)

In [18]:
df['price_difference'] = df['initial_price'] - df['final_price']

In [19]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,best_offer,more_offers,category,price_difference
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099,47.0,1099.0,INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899,0.0,899.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Truâ–ˆâ–ˆâ–ˆm Râ–ˆâ–ˆâ–ˆil,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999,0.0,999.0,INR,http://assets.myntassets.com/assets/images/174...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099,45.0,1099.0,INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts,0.0
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598,55.0,719.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,SUNâ–ˆâ–ˆâ–ˆE Câ–ˆâ–ˆâ–ˆTIOâ–ˆâ–ˆâ–ˆ,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts,879.0

# Saving the clean dataset

In [20]:
df.to_csv("cleaned_data/cleaned_tshirts.csv", index=False)

# Project Summary

In this project, data exploration and data cleaning operations were performed using Pandas.

The following tasks were completed successfully:

- Loaded the CSV dataset
- Explored dataset structure and columns
- Identified and handled missing values
- Removed highly missing columns
- Checked duplicate records
- Performed filtering and selection operations
- Converted data types for numerical analysis
- Created a derived column
- Saved the cleaned dataset as a new CSV file

This project helped in understanding the basics of data preprocessing and analysis using Python and Pandas.